CarModel/CarModel/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarModel.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string RegNr { get; set; }
        public string CarBrand { get; set; }
        public string CarModel { get; set; }
        public int CarTypeId { get; set; }
        public virtual CarType CarType { get; set; }
    }
}

CarModel/CarModel/Models/CarType.cs
using System.Collections.Generic;

namespace CarModel.Models
{
    public class CarType
    {
        public int Id { get; set; }
        public string Enginge { get; set; }
        public List<Car> Cars;
    }
}

CarModel/CarModel/ViewModels/CarViewModel.cs
using CarModel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarModel.ViewModels
{
    public class CarViewModel
    {
        public IEnumerable<Car> Cars { get; set; }
        public IEnumerable<CarType> CarTypes { get; set; }
    }
}

CarModel/CarModel/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CarModel.ViewModels;
using CarModel.Repository;
using CarModel.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CarModel.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarRepository _carRepository;
        private readonly ICarTypeRepository _carTypeRepository;

        public CarController(ICarRepository carRepository, ICarTypeRepository carTypeRepository)
        {
            _carRepository = carRepository;
            _carTypeRepository = carTypeRepository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.Cars = _carRepository.Cars;
            return View(carViewModel);
        }
        public IActionResult AddCarInfo()
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.CarTypes = _carTypeRepository.CarTypes;
            return View(carViewModel);
        }
        public IActionResult AddCar(string brand, string regNr,string carModel, int carTypeId)
        {
            var newCar = new Car { CarBrand = brand, RegNr = regNr,CarModel= carModel, CarTypeId = carTypeId };

            _carRepository.AddCarToDb(newCar);
            return RedirectToAction("Index", "Car");
        }

        public IActionResult DeleteCar()
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.Cars = _carRepository.Cars;
            return View(carViewModel);
        }
        public IActionResult Delete(int id)
        {
            _carRepository.DeleteCar(id);

            return RedirectToAction("Index", "Car");
        }

        public IActionResult Edit()
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.Cars = _carRepository.Cars;
            return View(carViewModel);
        }
        public IActionResult EditCar(int id, string brand, string regNr,string carModel, int carTypeId)
        {
            if (id != 0)
            {
                var updatingCar = _carRepository.GetCarById(id);

                updatingCar.CarBrand = brand;
                updatingCar.RegNr = regNr;
                updatingCar.CarModel = carModel;
                if (carTypeId == 0)
                {
                    return RedirectToAction("Error", "Shared");
                }
                else
                {
                    updatingCar.CarTypeId = carTypeId;
                }
                _carRepository.Edit(updatingCar);
                return RedirectToAction("Index", "Car");
            }
            else
            {
                return RedirectToAction("Error", "Shared");
            }
        }

        public IActionResult DetailsCar()
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.Cars = _carRepository.Cars;
            return View(carViewModel);
        }
        public IActionResult Details(int id)
        {

            var car = _carRepository.Cars;
            var lol = car.FirstOrDefault(c => c.Id == id);
            if (car == null)
                return NotFound();

            return View(lol);
        }
    }
}

CarModel/CarModel/Controllers/CarTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CarModel.ViewModels;
using CarModel.Models;
using CarModel.Repository;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CarModel.Controllers
{
    public class CarTypeController : Controller
    {
        private readonly ICarRepository _carRepository;
        private readonly ICarTypeRepository _carTypeRepository;

        public CarTypeController(ICarRepository carRepository, ICarTypeRepository carTypeRepository)
        {
            _carRepository = carRepository;
            _carTypeRepository = carTypeRepository;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddNewCarType()
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.CarTypes = _carTypeRepository.CarTypes;
            return View(carViewModel);
        }
        public IActionResult AddCarType(string engine)
        {
            var newEngine = new CarType { Enginge = engine };

            _carTypeRepository.AddCarTypeToDb(newEngine);

            return RedirectToAction("Index", "Car");
        }
        public IActionResult DeleteCarType()
        {
            CarViewModel carViewModel = new CarViewModel();
            carViewModel.CarTypes = _carTypeRepository.CarTypes;
            return View(carViewModel);
        }
        public IActionResult Delete(int id)
        {
            _carTypeRepository.DeleteCarType(id);

            return RedirectToAction("Index", "Car");
        }
    }
}

CarModel/CarModel/Views/Car/AddCarInfo.cshtml
<form action="@Url.Action("AddCar","Car")">
    <label for="brandId">Brand</label>
    <input id="brandId" name="brand" type="text" />
    <label for="regNrId">RegNr</label>
    <input id="regNrId" name="regNr" type="text" />
    <label for="carModel">carModel</label>
    <input id="carModel" name="carModel" type="text" />
    <label for="carTypeId">Engine</label>
    <input id="carTypeId" name="carTypeId" type="number" />

    <input type="submit" class="btn btn-primary" value="Submit" />
</form>
@model CarViewModel

@foreach (var carEngine in Model.CarTypes)
{
    <div>
        <p>Engine: @carEngine.Enginge, Id:@carEngine.Id</p>
    </div>

}

CarModel/CarModel/Views/Car/DeleteCar.cshtml
<form action="@Url.Action("Delete","Car")">
    <label for="Id">Remove Id</label>
    <input id="Id" name="Id" type="number" />

    <input type="submit" class="btn btn-primary" value="Submit" />
</form>
@model CarViewModel
<form action="@Url.Action("Index","Car")">
    @foreach (var car in Model.Cars)
    {
        <div>
            <p>Bil ID: @car.Id</p>
            <p>Bilmärke: @car.CarBrand</p>
            <p>RegNr: @car.RegNr</p>
            <p>BilModel: @car.CarModel</p>
            <p>Motor: @car.CarType.Enginge</p>
            <p>MotorId: @car.CarType.Id</p>
            <br />
        </div>
    }
</form>

CarModel/CarModel/Views/Car/Details.cshtml
@model Car
<div>
    <p>BilMärke: @Model.CarBrand</p>
    <p>RegNr: @Model.RegNr</p>
    <p>BilModel: @Model.CarModel</p>
    <p>Motor: @Model.CarType.Enginge</p>
</div>
<form action="@Url.Action("Index","Car")">
    <input type="submit" class="btn btn-primary" value="Back To List" />
</form>

CarModel/CarModel/Views/Car/DetailsCar.cshtml
<form action="@Url.Action("Details","Car")">
    <label for="Id">More Info</label>
    <input id="Id" name="Id" type="number" />

    <input type="submit" class="btn btn-primary" value="Submit" />
</form>
@model CarViewModel
<form action="@Url.Action("Index","Car")">
    @foreach (var car in Model.Cars)
    {
        <div>
            <p>Bil ID: @car.Id</p>
            <p>Bilmärke: @car.CarBrand</p>
            <p>RegNr: @car.RegNr</p>
            <p>Motor: @car.CarType.Enginge</p>
            <p>MotorId: @car.CarType.Id</p>
            <br />
        </div>
    }
</form>

CarModel/CarModel/Views/Car/Edit.cshtml
<form action="@Url.Action("EditCar","Car")">
    <label for="Id">Edit Car *</label>
    <input id="Id" name="Id" type="number" />
    <label for="brandId">Brand</label>
    <input id="brandId" name="brand" type="text" />
    <label for="regNrId">RegNr</label>
    <input id="regNrId" name="regNr" type="text" />
    <label for="carModel">carModel</label>
    <input id="carModel" name="carModel" type="text" />
    <label for="carTypeId">Engine *</label>
    <input id="carTypeId" name="carTypeId" type="number" />
    <input type="submit" class="btn btn-primary" value="Submit" />
</form>

@model CarViewModel

<form action="@Url.Action("Index","Car")">
    @foreach (var car in Model.Cars)
    {
        <div>
            <p>Bil ID: @car.Id</p>
            <p>Bilmärke: @car.CarBrand</p>
            <p>RegNr: @car.RegNr</p>
            <p>BilModel: @car.CarModel</p>
            <p>Motor: @car.CarType.Enginge</p>
            <p>MotorId: @car.CarType.Id</p>
            <br />
        </div>
    }
</form>

CarModel/CarModel/Views/Car/Index.cshtml
@model CarViewModel
<h1>Car</h1>
<form action="@Url.Action("AddCarInfo","Car")">
    <input type="submit" class="btn btn-primary" value="Add Car" />
</form>
<form action="@Url.Action("DeleteCar","Car")">
    <input type="submit" class="btn btn-primary" value="Delete Car" />
</form>
<form action="@Url.Action("Edit","Car")">
    <input type="submit" class="btn btn-primary" value="Edit Car" />
</form>
<form action="@Url.Action("DetailsCar","Car")">
    <input type="submit" class="btn btn-primary" value="CarDetails" />
</form>
<h1>CarType</h1>
<form action="@Url.Action("AddNewCarType","CarType")">
    <input type="submit" class="btn btn-primary" value="Add CarType" />
</form>
<form action="@Url.Action("DeleteCarType","CarType")">
    <input type="submit" class="btn btn-primary" value="Delete CarType" />
</form>

<form action="@Url.Action("Index","Car")">
    @foreach (var car in Model.Cars)
    {
        <div>
            <p>Bil ID: @car.Id</p>
            <p>Bilmärke: @car.CarBrand</p>
            <p>RegNr: @car.RegNr</p>
            <p>BilModel: @car.CarModel</p>
            <p>Motor: @car.CarType.Enginge</p>
            <p>MotorId: @car.CarType.Id</p>
            <br />
        </div>
    }
</form>